const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Browser,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.JavaScriptInEvents.Logo_Event2_Act2,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Tween.Acts.TweenTwoProperties
	];
};
self.C3_JsPropNameTable = [
	{logobg: 0},
	{logo: 0},
	{pokiiFuns: 0},
	{tildbg: 0},
	{ui: 0},
	{bord: 0},
	{Tween: 0},
	{playbt: 0},
	{bg2: 0},
	{Text: 0},
	{frame: 0},
	{id: 0},
	{id2: 0},
	{id3: 0},
	{Sine: 0},
	{ballons: 0},
	{Touch: 0},
	{soundbtn: 0},
	{pausebtn: 0},
	{resumebtn: 0},
	{restartbtn: 0},
	{Sprite2: 0},
	{Text2: 0},
	{Audio: 0},
	{AJAX: 0},
	{JSON: 0},
	{Browser: 0},
	{level1: 0},
	{level2: 0},
	{level3: 0},
	{level4: 0},
	{level5: 0},
	{lv1: 0},
	{lv2: 0},
	{lv3: 0},
	{lv4: 0},
	{lv5: 0},
	{color2: 0},
	{spawner: 0},
	{Bullet: 0},
	{arrow: 0},
	{black: 0},
	{check: 0},
	{sound: 0},
	{level: 0},
	{levelcheck: 0},
	{over: 0},
	{arrws: 0},
	{balloons: 0},
	{WIN: 0}
];

self.InstanceType = {
	logobg: class extends self.ITiledBackgroundInstance {},
	logo: class extends self.ISpriteInstance {},
	pokiiFuns: class extends self.ISpriteInstance {},
	tildbg: class extends self.ITiledBackgroundInstance {},
	ui: class extends self.ISpriteInstance {},
	bord: class extends self.ISpriteInstance {},
	playbt: class extends self.ISpriteInstance {},
	bg2: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	ballons: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	soundbtn: class extends self.ISpriteInstance {},
	pausebtn: class extends self.ISpriteInstance {},
	resumebtn: class extends self.ISpriteInstance {},
	restartbtn: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Browser: class extends self.IInstance {},
	spawner: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	black: class extends self.ISpriteInstance {}
}