const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.LOS,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Behaviors.scrollto,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.viewporttop,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.TiledBg.Cnds.IsOnScreen,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Acts.SetPos
	];
};
self.C3_JsPropNameTable = [
	{bg: 0},
	{notEatable: 0},
	{Tween: 0},
	{LineOfSight: 0},
	{food: 0},
	{ang: 0},
	{sec: 0},
	{id: 0},
	{Bullet: 0},
	{enemHead: 0},
	{mainplayer: 0},
	{enemBody: 0},
	{index: 0},
	{delay: 0},
	{mainbody: 0},
	{Solid: 0},
	{border: 0},
	{Mouse: 0},
	{ScrollTo: 0},
	{camera: 0},
	{Particles: 0},
	{pausebtn: 0},
	{bd26_jpkv_: 0},
	{playbtn: 0},
	{type: 0},
	{coinCount: 0},
	{food2: 0},
	{Touch: 0},
	{Browser: 0},
	{PlatformInfo: 0},
	{Text: 0},
	{dd: 0},
	{IMG_: 0},
	{pokiiFuns: 0},
	{iPhone16Pro: 0},
	{TiledBackground: 0},
	{enem: 0},
	{player: 0},
	{mouseX: 0},
	{mouseY: 0},
	{foodcount: 0},
	{applecount: 0},
	{coincount: 0},
	{eggcount: 0},
	{check10: 0},
	{check50: 0}
];

self.InstanceType = {
	bg: class extends self.ITiledBackgroundInstance {},
	food: class extends self.ISpriteInstance {},
	enemHead: class extends self.ISpriteInstance {},
	mainplayer: class extends self.ISpriteInstance {},
	enemBody: class extends self.ISpriteInstance {},
	mainbody: class extends self.ISpriteInstance {},
	border: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	camera: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	pausebtn: class extends self.ISpriteInstance {},
	bd26_jpkv_: class extends self.ISpriteInstance {},
	playbtn: class extends self.ISpriteInstance {},
	coinCount: class extends self.ITextInstance {},
	food2: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	dd: class extends self.ISpriteInstance {},
	IMG_: class extends self.ISpriteInstance {},
	pokiiFuns: class extends self.ISpriteInstance {},
	iPhone16Pro: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	enem: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {}
}