const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.JavaScriptInEvents.Logo_Event3_Act2,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Text.Cnds.IsOnScreen,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Arr.Exps.CurY
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{iPhone16Pro: 0},
	{pokiiFuns: 0},
	{Sprite2: 0},
	{Text: 0},
	{Text2: 0},
	{AJAX: 0},
	{JSON: 0},
	{table: 0},
	{Tween: 0},
	{egg: 0},
	{uitxt: 0},
	{check: 0},
	{eggtxt: 0},
	{eggicon: 0},
	{Sprite: 0},
	{overtxt: 0},
	{Touch: 0},
	{Audio: 0},
	{cross: 0},
	{type: 0},
	{filled: 0},
	{tile: 0},
	{currentgame: 0},
	{levelcheck: 0},
	{level: 0},
	{sound: 0},
	{eggcount: 0},
	{seconds: 0},
	{over: 0},
	{cellsize: 0},
	{cols: 0},
	{startX: 0},
	{startY: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	iPhone16Pro: class extends self.ISpriteInstance {},
	pokiiFuns: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	table: class extends self.ISpriteInstance {},
	egg: class extends self.ISpriteInstance {},
	uitxt: class extends self.ISpriteInstance {},
	eggtxt: class extends self.ITextInstance {},
	eggicon: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	overtxt: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	cross: class extends self.ISpriteInstance {},
	tile: class extends self.ISpriteInstance {},
	currentgame: class extends self.IArrayInstance {}
}