const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Behaviors.Physics,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.JavaScriptInEvents.Logo_Event2_Act2,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Acts.SetLayoutAngle,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Physics.Acts.SetAwake,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Cnds.IsOnScreen,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportright
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{JSON: 0},
	{Touch: 0},
	{Audio: 0},
	{pokiiFuns: 0},
	{iPhone16Pro: 0},
	{check: 0},
	{Text: 0},
	{Tween: 0},
	{Physics: 0},
	{playbt: 0},
	{Sprite2: 0},
	{grasss: 0},
	{ScrollTo: 0},
	{ball: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{Pin: 0},
	{arrows: 0},
	{TiledBackground3: 0},
	{logo: 0},
	{bglogo: 0},
	{TiledBackground4: 0},
	{hole: 0},
	{power: 0},
	{Sprite3: 0},
	{circle: 0},
	{DragDrop: 0},
	{drager: 0},
	{dist: 0},
	{joystick: 0},
	{pausebtn: 0},
	{soundbtn: 0},
	{Text2: 0},
	{Sprite: 0},
	{btn: 0},
	{Sprite4: 0},
	{Browser: 0},
	{candrag: 0},
	{aimangle: 0},
	{moving: 0},
	{sound: 0},
	{chance: 0},
	{state: 0},
	{level: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	pokiiFuns: class extends self.ISpriteInstance {},
	iPhone16Pro: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	playbt: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	grasss: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	arrows: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	logo: class extends self.ISpriteInstance {},
	bglogo: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	hole: class extends self.ISpriteInstance {},
	power: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	circle: class extends self.ISpriteInstance {},
	drager: class extends self.ISpriteInstance {},
	joystick: class extends self.ISpriteInstance {},
	pausebtn: class extends self.ISpriteInstance {},
	soundbtn: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	btn: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {}
}